// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlmfmafmoomxoipchgwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbWZtYWZtb29teG9pcGNoZ3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzgzNjAsImV4cCI6MjA2Mzg1NDM2MH0.VmOiT8XU5c7g_fY-rq2N9CXoZhEBOZEPc-Q4aa78WPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);