// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipjhzesaxyntvzdyywmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlwamh6ZXNheHludHZ6ZHl5d21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODM2NDMsImV4cCI6MjA2NDk1OTY0M30.oYvL06NJ5_nhJEAJ-FNBy39dl1GVu_IpaQpb7YJ9fRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);